# Generated by Django 3.2.5 on 2021-07-29 03:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('Author_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'db_table': 'AUTHORS',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Isbn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('Title', models.TextField()),
            ],
            options={
                'db_table': 'BOOK',
            },
        ),
        migrations.CreateModel(
            name='Book_Loans',
            fields=[
                ('Loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_out', models.DateField()),
                ('Due_Date', models.DateField(default=datetime.datetime(2021, 8, 11, 23, 16, 14, 253706))),
                ('Date_in', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Book_Loans',
                'db_table': 'BOOK_LOANS',
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('Card_id', models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('Ssn', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{3}[-]{1}[0-9]{2}[-]{1}[0-9]{4}$', 'Valid ssn is required! \nMust be in form: 123-45-6789')])),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^[(]{1}[0-9]{3}[)]{1}[ ]{1}[0-9]{3}[-]{1}[0-9]{4}$', 'Valid Phone number is required! \nMust be in form: (123) 456-7890')])),
            ],
            options={
                'db_table': 'BORROWER',
            },
        ),
        migrations.CreateModel(
            name='Fines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fine_amt', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('Paid', models.BooleanField(default=False)),
                ('Loan_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library_app.book_loans')),
            ],
            options={
                'verbose_name_plural': 'Fines',
                'db_table': 'FINES',
            },
        ),
        migrations.AddField(
            model_name='book_loans',
            name='Card_id',
            field=models.ForeignKey(default='ID000000', on_delete=django.db.models.deletion.CASCADE, to='library_app.borrower'),
        ),
        migrations.AddField(
            model_name='book_loans',
            name='Isbn',
            field=models.ForeignKey(default='0000000001', on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
        ),
        migrations.CreateModel(
            name='Book_Authors',
            fields=[
                ('Book_Authors_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.authors')),
                ('Isbn', models.ForeignKey(default='0000000001', on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
            ],
            options={
                'verbose_name_plural': 'Book_Authors',
                'db_table': 'BOOK_AUTHORS',
            },
        ),
    ]
