# Generated by Django 3.2.5 on 2021-07-29 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loans',
            name='Due_Date',
            field=models.DateField(default=datetime.datetime(2021, 8, 12, 0, 23, 14, 686754)),
        ),
    ]
