# Generated by Django 3.2.5 on 2021-07-30 07:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_loans_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loans',
            name='Due_Date',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 3, 0, 4, 261745)),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='Phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[(]{1}[0-9]{3}[)]{1}[ ]{1}[0-9]{3}[-]{1}[0-9]{4}$', 'Valid Phone number is required! \nMust be in form: (123) 456-7890')]),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='Ssn',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{3}[-]{1}[0-9]{2}[-]{1}[0-9]{4}$', 'Valid ssn is required! \nMust be in form: 123-45-6789')]),
        ),
    ]
