# Generated by Django 3.2.5 on 2021-07-31 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20210730_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loans',
            name='Due_Date',
            field=models.DateField(default=datetime.datetime(2021, 8, 13, 21, 0, 7, 37750)),
        ),
    ]
