# Generated by Django 3.2.5 on 2021-07-31 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_loans_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_loans',
            name='Due_Date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 13, 21, 37, 10, 86551), null=True),
        ),
    ]
